version: "3.8"

volumes:
  wordpress:
  wordpress_db:
  wordpress_conf:

services:
  wordpress:
    build:
      context: .
    container_name: wordpress_yokofolio
    depends_on:
      - wordpress_db
    ports:
      - "${WEB_HOST_PORT}:80"
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - wordpress_conf:/var/www/html
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${HOST_NAME}
      HOSTNAME: ${HOST_NAME}
    networks:
      - webserver
      - default

  #WP DB
  wordpress_db:
    container_name: mysql_yokofolio
    image: mysql:5.7
    restart: unless-stopped
    user: 1000:1000
    env_file: .env
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      VIRTUAL_HOST: ${HOST_NAME}
      HOSTNAME: ${HOST_NAME}

networks:
  webserver:
    external: true