name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: compile SCSS
      run: |
        npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        rsync -v -avz \
        -e "ssh -vvv -o StrictHostKeyChecking=no -p 10022" \
        --exclude=".git/" \
        --exclude=".github/" \
        --exclude="*.example" \
        --exclude=".gitignore" \
        --exclude="docker-compose.yaml" \
        --exclude="Dockerfile" \
        --exclude="*.json" \
        --exclude="README.md" \
        "$GITHUB_WORKSPACE"/ \
        yokofolio@162.43.106.92:/home/yokofolio/yokofolio.cloudfree.jp/public_html/wp-content/themes/yokofolio